### ISSUE TITLE
No Accounts Configured!

### ISSUE THREAD

**Issue by zzzgithubzzz** [deanishe/alfred-gcal#93] opened 2020-10-01 12:04 UTC
Hi,

Thank you for this workflow. I am trying to use your workflow. However, I keep getting the warning 'No Accounts Configured' even after repeatedly giving explicit access to my google account.

Am stuck now. How do I get around?

**Comment by deanishe** [comment] 2020-10-01 21:55
Duplicate of #33 and #49.

Please search for your problem in existing issues before creating a new one.

**Closed as completed** 2020-10-01 21:55 UTC
Labels: duplicate

**Comment by zzzgithubzzz** [comment] 2020-10-05 09:03
Hi Dean,

Thank you for pointing me to the links that has the problem addressed.

The solutions worked for me as well after changing the default browser to safari.

Cheers!

Vinod
